//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherSchoolApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationGMO
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Event { get; set; }
        public int TeacherId { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
